'NoneType' object is not callable网络连接失败 2017-03-25 06:56:34,600 stats.py[line:108]                      WARNING 
